export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum CompanySector {
  AGRICULTURE = 'AGRICULTURE',
  INDUSTRIES_MANUFACTURIERES = 'INDUSTRIES MANUFACTURIÈRES',
  ENERGIE = 'ENERGIE',
  EAUDECHETS = 'EAU DECHETS',
  BTP = 'BTP',
  COMMERCE = 'COMMERCE',
  TRANSPORT = 'TRANSPORT',
  HEBERGEMENT_RESTAURATION = 'HEBERGEMENT RESTAURATION',
  INFORMATION_COMMUNICATION = 'INFORMATION COMMUNICATION',
  FINANCE_ASSURANCE = 'FINANCE ASSURANCE',
  IMMOBILIER = 'IMMOBILIER',
  SCIENCES_TECHNIQUE = 'SCIENCES TECHNIQUE',
  ADMINISTRATION_PUBLIQUE = 'ADMINISTRATION PUBLIQUE',
  ENSEIGNEMENT = 'ENSEIGNEMENT',
  SANTE_SOCIAL = 'SANTE SOCIAL',
  ARTS_SPECTACLES_LOISIRS = 'ARTS SPECTACLES LOISIRS',
  ACTIVITES_EXTRA_TERRITORIALES = 'ACTIVITES EXTRA TERRITORIALES',
  SERVICES_AUTRES = 'SERVICES AUTRES',
}

export enum Hiring {
  ONGOING = 'ONGOING',
  DEACTIVATE = 'DEACTIVATE',
}
