export enum EmploymentSector {
  AGRICULTURE = 'AGRICULTURE',
  INDUSTRIES_MANUFACTURIERES = 'INDUSTRIES_MANUFACTURIÈRES',
  ENERGIE = 'ENERGIE',
  EAUDECHETS = 'EAU_DECHETS',
  BTP = 'BTP',
  COMMERCE = 'COMMERCE',
  TRANSPORT = 'TRANSPORT',
  HEBERGEMENT_RESTAURATION = 'HEBERGEMENT_RESTAURATION',
  INFORMATION_COMMUNICATION = 'INFORMATION_COMMUNICATION',
  FINANCE_ASSURANCE = 'FINANCE_ASSURANCE',
  IMMOBILIER = 'IMMOBILIER',
  SCIENCES_TECHNIQUE = 'SCIENCES_TECHNIQUE',
  ADMINISTRATION_PUBLIQUE = 'ADMINISTRATION_PUBLIQUE',
  ENSEIGNEMENT = 'ENSEIGNEMENT',
  SANTE_SOCIAL = 'SANTE_SOCIAL',
  ARTS_SPECTACLES_LOISIRS = 'ARTS_SPECTACLES_LOISIRS',
  ACTIVITES_EXTRA_TERRITORIALES = 'ACTIVITES_EXTRA_TERRITORIALES',
  SERVICES_AUTRES = 'SERVICES_AUTRES',
}

export enum Hiring {
  ONGOING = 'ONGOING',
  DEACTIVATE = 'DEACTIVATE',
}
